### ISSUE TITLE
es3 repo not accessible

### ISSUE THREAD

**Issue by MocquillonCedric** [Greatness7/tes3conv#2]
Hi. First of all thank you for your great tool! I have an issue when I want to build from source: it seems that the es3 dependency repository is not accessible, when I click on this link: https://github.com/Greatness7/es3_rust/tree/502d988fc647a245bddfac25bb11ca9445ffd2c4
I have a 404 error.
If I try to clone from git command line it is not able to retrieve this submodule.

**Comment by datatypevoid** [comment]
Is there a public facing source for this dependency?

**Comment by datatypevoid** [comment]
Not sure how I missed this while searching, but someone pointed me in the right direction: https://github.com/Greatness7/tes3

**Comment by Greatness7** [comment]
Source is available at <https://github.com/Greatness7/tes3>
